apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: demo-app
  namespace: argo-demo
spec:
  ports:
    - name: "api"
      port: 3000
      targetPort: 3000
  selector:
    app: demo
